# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/rubyx/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),rubyx)

$(call add-radio-file-sha1-checked,radio/audio_dsp.img,79a5e4885111a0601a47c1113b5fac7ec112a86d)
$(call add-radio-file-sha1-checked,radio/cam_vpu1.img,a0a649ca1a589d8b3c332b8ab7d58a427cfae7f7)
$(call add-radio-file-sha1-checked,radio/cam_vpu2.img,abd5490462ab07f43ba21f6be48b641a26ee67ba)
$(call add-radio-file-sha1-checked,radio/cam_vpu3.img,817cda4129f3c43c5841087d0e4ca8a73d237a61)
$(call add-radio-file-sha1-checked,radio/dpm.img,03870ceabda73293959bfeeadd703ad20873bfa6)
$(call add-radio-file-sha1-checked,radio/gz.img,b33692465e10d1e7ada9f44d66cc9f83a26b16c1)
$(call add-radio-file-sha1-checked,radio/lk.img,d8ca641bbdba9abd49b10b30a540c7b3abf5793d)
$(call add-radio-file-sha1-checked,radio/logo.img,ab7007ea4209dbf7a8925fe86246486418ceb87a)
$(call add-radio-file-sha1-checked,radio/mcupm.img,4009b6f3462e438acd2ab757010aaee22f739e4e)
$(call add-radio-file-sha1-checked,radio/md1img.img,4ec07833ecf36de44c862a43e5c41fb5f5acaca4)
$(call add-radio-file-sha1-checked,radio/pi_img.img,b0dd209122a5d78f71069871133308028824c99c)
$(call add-radio-file-sha1-checked,radio/preloader_raw.img,d40fdafe98737a540def573b8ccee2d466bbc85f)
$(call add-radio-file-sha1-checked,radio/scp.img,db0dbb25eff830d948f200d16662ba395b6bc409)
$(call add-radio-file-sha1-checked,radio/spmfw.img,02ebc09cf6d4b07cdf44f5e9b828b0b8cad1e7b6)
$(call add-radio-file-sha1-checked,radio/sspm.img,873a9315cd087126b81e78a944d771113880796f)
$(call add-radio-file-sha1-checked,radio/tee.img,2331ba5260016aa2c5831fc3a83fd1c6c5933975)

endif
